# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\python\browser\setting.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgSetting(object):
    def setupUi(self, DlgSetting):
        DlgSetting.setObjectName("DlgSetting")
        DlgSetting.resize(492, 323)
        DlgSetting.setProperty("sizeGripEnabled", True)
        self.gridLayout = QtWidgets.QGridLayout(DlgSetting)
        self.gridLayout.setObjectName("gridLayout")
        self.group_toolbar = QtWidgets.QGroupBox(DlgSetting)
        self.group_toolbar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.group_toolbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.group_toolbar.setStyleSheet("QGroupBox{\n"
"    border:none;\n"
"}")
        self.group_toolbar.setTitle("")
        self.group_toolbar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.group_toolbar.setFlat(False)
        self.group_toolbar.setObjectName("group_toolbar")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.group_toolbar)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btn_apply = QtWidgets.QPushButton(self.group_toolbar)
        self.btn_apply.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_apply.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_apply.setAutoDefault(False)
        self.btn_apply.setDefault(False)
        self.btn_apply.setObjectName("btn_apply")
        self.gridLayout_9.addWidget(self.btn_apply, 0, 2, 1, 1)
        self.btn_cancel = QtWidgets.QPushButton(self.group_toolbar)
        self.btn_cancel.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_cancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_cancel.setAutoFillBackground(False)
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout_9.addWidget(self.btn_cancel, 0, 0, 1, 1)
        self.btn_ok = QtWidgets.QPushButton(self.group_toolbar)
        self.btn_ok.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_ok.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_ok.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_ok.setAutoFillBackground(False)
        self.btn_ok.setCheckable(False)
        self.btn_ok.setAutoDefault(False)
        self.btn_ok.setDefault(True)
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout_9.addWidget(self.btn_ok, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.group_toolbar, 2, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tab_other = QtWidgets.QTabWidget(DlgSetting)
        self.tab_other.setTabsClosable(False)
        self.tab_other.setObjectName("tab_other")
        self.tab_common = QtWidgets.QWidget()
        self.tab_common.setObjectName("tab_common")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_common)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.group_theme = QtWidgets.QGroupBox(self.tab_common)
        self.group_theme.setMinimumSize(QtCore.QSize(0, 0))
        self.group_theme.setStyleSheet("")
        self.group_theme.setObjectName("group_theme")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_theme)
        self.gridLayout_4.setContentsMargins(9, 9, -1, -1)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.combo_theme = QtWidgets.QComboBox(self.group_theme)
        self.combo_theme.setObjectName("combo_theme")
        self.gridLayout_4.addWidget(self.combo_theme, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.group_theme, 0, 0, 1, 1)
        self.group_ui = QtWidgets.QGroupBox(self.tab_common)
        self.group_ui.setMinimumSize(QtCore.QSize(0, 50))
        self.group_ui.setObjectName("group_ui")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_ui)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chk_close_to_tray = QtWidgets.QCheckBox(self.group_ui)
        self.chk_close_to_tray.setEnabled(True)
        self.chk_close_to_tray.setChecked(False)
        self.chk_close_to_tray.setObjectName("chk_close_to_tray")
        self.verticalLayout.addWidget(self.chk_close_to_tray)
        self.chk_close_confirm = QtWidgets.QCheckBox(self.group_ui)
        self.chk_close_confirm.setChecked(True)
        self.chk_close_confirm.setObjectName("chk_close_confirm")
        self.verticalLayout.addWidget(self.chk_close_confirm)
        self.gridLayout_7.addWidget(self.group_ui, 1, 0, 1, 1)
        self.group_savepath = QtWidgets.QGroupBox(self.tab_common)
        self.group_savepath.setMinimumSize(QtCore.QSize(0, 50))
        self.group_savepath.setObjectName("group_savepath")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_savepath)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_savepath = QtWidgets.QLineEdit(self.group_savepath)
        self.txt_savepath.setReadOnly(True)
        self.txt_savepath.setObjectName("txt_savepath")
        self.gridLayout_2.addWidget(self.txt_savepath, 0, 0, 1, 1)
        self.btn_browse_savepath = QtWidgets.QPushButton(self.group_savepath)
        self.btn_browse_savepath.setObjectName("btn_browse_savepath")
        self.gridLayout_2.addWidget(self.btn_browse_savepath, 0, 1, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.group_savepath)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_2.addWidget(self.btn_clear, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.group_savepath, 2, 0, 1, 1)
        self.tab_other.addTab(self.tab_common, "")
        self.tab_printer = QtWidgets.QWidget()
        self.tab_printer.setObjectName("tab_printer")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_printer)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.group_printer = QtWidgets.QGroupBox(self.tab_printer)
        self.group_printer.setMinimumSize(QtCore.QSize(0, 0))
        self.group_printer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_printer.setObjectName("group_printer")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_printer)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rdo_portrait = QtWidgets.QRadioButton(self.group_printer)
        self.rdo_portrait.setChecked(True)
        self.rdo_portrait.setObjectName("rdo_portrait")
        self.gridLayout_5.addWidget(self.rdo_portrait, 0, 1, 1, 1)
        self.rdo_landscape = QtWidgets.QRadioButton(self.group_printer)
        self.rdo_landscape.setAutoRepeat(False)
        self.rdo_landscape.setObjectName("rdo_landscape")
        self.gridLayout_5.addWidget(self.rdo_landscape, 0, 2, 1, 1)
        self.combo_printer_list = QtWidgets.QComboBox(self.group_printer)
        self.combo_printer_list.setObjectName("combo_printer_list")
        self.gridLayout_5.addWidget(self.combo_printer_list, 0, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 4)
        self.gridLayout_6.addWidget(self.group_printer, 0, 0, 1, 1)
        self.group_other = QtWidgets.QGroupBox(self.tab_printer)
        self.group_other.setObjectName("group_other")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.group_other)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chk_fullpage = QtWidgets.QCheckBox(self.group_other)
        self.chk_fullpage.setObjectName("chk_fullpage")
        self.horizontalLayout.addWidget(self.chk_fullpage)
        self.btn_test = QtWidgets.QPushButton(self.group_other)
        self.btn_test.setObjectName("btn_test")
        self.horizontalLayout.addWidget(self.btn_test)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout_6.addWidget(self.group_other, 3, 0, 1, 1)
        self.group_document = QtWidgets.QGroupBox(self.tab_printer)
        self.group_document.setMinimumSize(QtCore.QSize(0, 80))
        self.group_document.setObjectName("group_document")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_document)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_margin = QtWidgets.QLabel(self.group_document)
        self.lbl_margin.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_margin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl_margin.setObjectName("lbl_margin")
        self.gridLayout_3.addWidget(self.lbl_margin, 1, 0, 1, 1)
        self.txt_font = QtWidgets.QLineEdit(self.group_document)
        self.txt_font.setReadOnly(True)
        self.txt_font.setObjectName("txt_font")
        self.gridLayout_3.addWidget(self.txt_font, 0, 1, 1, 1)
        self.lbl_font = QtWidgets.QLabel(self.group_document)
        self.lbl_font.setObjectName("lbl_font")
        self.gridLayout_3.addWidget(self.lbl_font, 0, 0, 1, 1)
        self.btn_font = QtWidgets.QPushButton(self.group_document)
        self.btn_font.setObjectName("btn_font")
        self.gridLayout_3.addWidget(self.btn_font, 0, 2, 1, 1)
        self.txt_margin = QtWidgets.QDoubleSpinBox(self.group_document)
        self.txt_margin.setDecimals(0)
        self.txt_margin.setMaximum(9999.0)
        self.txt_margin.setObjectName("txt_margin")
        self.gridLayout_3.addWidget(self.txt_margin, 1, 1, 1, 2)
        self.gridLayout_6.addWidget(self.group_document, 1, 0, 1, 1)
        self.tab_other.addTab(self.tab_printer, "")
        self.gridLayout.addWidget(self.tab_other, 1, 0, 1, 1)

        self.retranslateUi(DlgSetting)
        self.tab_other.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DlgSetting)

    def retranslateUi(self, DlgSetting):
        _translate = QtCore.QCoreApplication.translate
        DlgSetting.setWindowTitle(_translate("DlgSetting", "Setting"))
        self.btn_apply.setText(_translate("DlgSetting", "Apply"))
        self.btn_cancel.setText(_translate("DlgSetting", "Cancel"))
        self.btn_ok.setText(_translate("DlgSetting", "OK"))
        self.group_theme.setTitle(_translate("DlgSetting", "Theme"))
        self.group_ui.setTitle(_translate("DlgSetting", "User interface"))
        self.chk_close_to_tray.setText(_translate("DlgSetting", "Close to system tray"))
        self.chk_close_confirm.setText(_translate("DlgSetting", "Closing confirmation"))
        self.group_savepath.setTitle(_translate("DlgSetting", "Default file save directory"))
        self.btn_browse_savepath.setText(_translate("DlgSetting", "Select"))
        self.btn_clear.setText(_translate("DlgSetting", "Clear"))
        self.tab_other.setTabText(self.tab_other.indexOf(self.tab_common), _translate("DlgSetting", "Common"))
        self.group_printer.setTitle(_translate("DlgSetting", "Printer"))
        self.rdo_portrait.setText(_translate("DlgSetting", "Portrait"))
        self.rdo_landscape.setText(_translate("DlgSetting", "Landscape"))
        self.group_other.setTitle(_translate("DlgSetting", "Printing"))
        self.chk_fullpage.setText(_translate("DlgSetting", "Fullpage printing"))
        self.btn_test.setText(_translate("DlgSetting", "Test"))
        self.group_document.setTitle(_translate("DlgSetting", "Document"))
        self.lbl_margin.setText(_translate("DlgSetting", "Margin"))
        self.lbl_font.setText(_translate("DlgSetting", "Font"))
        self.btn_font.setText(_translate("DlgSetting", "Select"))
        self.tab_other.setTabText(self.tab_other.indexOf(self.tab_printer), _translate("DlgSetting", "Printer"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgSetting = QtWidgets.QWidget()
    ui = Ui_DlgSetting()
    ui.setupUi(DlgSetting)
    DlgSetting.show()
    sys.exit(app.exec_())
